import {test,expect} from '@playwright/test';
import {decodeState} from '../../encounters/engine.mjs';
const current=page=>decodeState(new URL(page.url()).hash.slice(11).split('~')[0]);
for(const role of ['public','garda'])test(`${role} character choice, changes and counterpart survive the full encounter`,async({page})=>{
 const other=role==='public'?'garda':'public',errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:390,height:844});
 await page.goto((role==='public'?'./':'garda/')+'#encounters/'+role);
 await page.locator('[data-action="paired-setup-characters"]').click();
 await expect(page.locator('.character-option')).toHaveCount(9);
 await expect.poll(()=>page.locator('.character-image img').evaluateAll(images=>images.every(img=>img.complete&&img.naturalWidth>0))).toBe(true);
 const chosen=page.locator(`[data-character="${role}-6"]`);
 await chosen.focus();await page.keyboard.press('Space');
 await expect(page.locator(`[data-character="${role}-6"]`)).toHaveAttribute('aria-pressed','true');
 await expect(page.locator(`[data-character="${role}-6"]`)).toBeFocused();
 await page.reload();await page.locator('[data-action="paired-setup-characters"]').click();await expect(page.locator(`[data-character="${role}-6"]`)).toHaveAttribute('aria-pressed','true');
 await page.locator('[data-action="paired-setup-done"]').click();
 await page.locator('[data-action="paired-quick-start"]').click();
 await expect(page.locator('.paired-game')).toBeVisible();
 const initial=current(page);expect(initial.cast[role]).toBe(role+'-6');expect(initial.cast[other]).toMatch(new RegExp('^'+other+'-[1-9]$'));
 await expect(page.locator('.cast-character.is-you')).toHaveAttribute('data-character-id',role+'-6');
 await page.locator('[data-action="paired-answer"]').first().click();await expect(page.locator('#feedback')).toBeVisible();
 const answered=current(page);
 await page.locator('[data-action="paired-characters"]').click();await expect(page.locator('#character-picker-title')).toBeFocused();
 await page.locator(`[data-character="${role}-9"]`).click();
 expect(current(page).answers).toEqual(answered.answers);expect(current(page).nodeId).toBe(answered.nodeId);
 expect(current(page).cast).toEqual({...initial.cast,[role]:role+'-9'});
 await page.locator('[data-action="paired-character-close"]').click();await expect(page.locator('[data-action="paired-characters"]')).toBeFocused();
 await page.locator('.perspective-bar [data-action="paired-switch"]').click();
 await expect(page.locator('.cast-character.is-you')).toHaveAttribute('data-character-id',initial.cast[other]);
 await page.locator('[data-action="paired-characters"]').click();await page.locator(`[data-character="${other}-4"]`).click();
 const cast={[role]:role+'-9',[other]:other+'-4'};expect(current(page).cast).toEqual(cast);
 await page.locator('[data-action="paired-character-close"]').click();
 const saved=current(page);await page.reload();await expect(page.locator('.paired-game')).toBeVisible();expect(current(page)).toEqual(saved);
 await page.locator('[data-site-switch]').click();await expect(page.locator('.paired-game')).toBeVisible();expect(current(page).cast).toEqual(cast);expect(current(page).answers).toEqual(saved.answers);
 await page.locator('.header [data-reading-open]').click();await page.locator('#reading-language').selectOption('ga');await page.locator('#reading-form [type="submit"]').click();
 await expect(page.getByRole('button',{name:'Athraigh carachtar',exact:true})).toBeVisible();expect(current(page).cast).toEqual(cast);
 for(let i=0;i<10&&!current(page).complete;i++){
  if(current(page).answers[current(page).role]===null)await page.locator('[data-action="paired-answer"]').first().click();
  await page.locator('[data-action="paired-next"]').click();
  await expect.poll(()=>current(page).complete||current(page).answers[current(page).role]===null).toBe(true);
  expect(current(page).cast).toEqual(cast);
 }
 expect(current(page).complete).toBe(true);await expect(page.locator('.paired-recap')).toBeVisible();
 await page.getByRole('button',{name:'Athraigh carachtar',exact:true}).click();
 await page.locator(`[data-character="${current(page).role}-2"]`).click();
 expect(current(page).complete).toBe(true);expect(current(page).cast[current(page).role]).toBe(current(page).role+'-2');
 await page.locator('[data-action="paired-character-close"]').click();
 await page.locator('[data-action="paired-revisit"]').first().click();await expect(page.locator('.paired-game')).toBeVisible();
 expect(current(page).cast[current(page).role]).toBe(current(page).role+'-2');expect(errors).toEqual([]);
});
