import {test,expect} from '@playwright/test';
import {decodeState} from '../../encounters/engine.mjs';

const state=page=>decodeState(new URL(page.url()).hash.slice(11).split('~')[0]);
for(const role of ['public','garda'])test(`${role} can start immediately or browse, then learn from a choice`,async({page})=>{
 await page.setViewportSize({width:390,height:844});
 await page.goto(role==='public'?'./':'garda/');
 await expect(page.getByText('Know your rights. Understand fair decisions.',{exact:true})).toBeVisible();
 await page.locator(`.perspective-hero a[href="#encounters/${role}"]`).click();
 await expect(page.locator('[data-action="paired-quick-start"]')).toBeVisible();
 await expect(page.locator('.character-option')).toHaveCount(0);
 await expect(page.locator('.scenario-library')).not.toHaveAttribute('open','');
 await expect(page.locator('[data-action="paired-start"]:visible')).toHaveCount(0);
 await page.locator('[data-action="paired-setup-characters"]').click();
 await expect(page.locator('#character-picker-title')).toBeFocused();
 await page.locator('[data-action="paired-setup-characters"]').click();
 await expect(page.locator('[data-action="paired-setup-characters"]')).toBeFocused();
 await expect(page.locator('.character-option')).toHaveCount(0);
 await page.locator('[data-action="paired-quick-start"]').click();
 await expect(page.locator('#scene-title')).toBeFocused();
 expect(state(page).id).toBe(role+'-street');
 expect(state(page).role).toBe(role);
 await expect(page.locator('.role-scores')).not.toBeVisible();
 await expect(page.locator('[data-action="paired-switch"]')).toHaveCount(1);
 const before=state(page);
 await page.locator('[data-action="paired-answer"]').first().click();
 await expect(page.locator('#feedback')).toBeFocused();
 await expect(page.locator('[data-action="paired-next"]')).toBeVisible();
 const answered=state(page);
 await page.locator('.play-help summary').click();
 await expect(page.locator('.role-scores')).toBeVisible();
 expect(state(page)).toEqual(answered);
 await page.locator('[data-action="paired-change"]').click();
 await expect(page.locator('#choice-title')).toBeFocused();
 expect(state(page).answers[role]).toBeNull();
 expect(state(page).cast).toEqual(before.cast);
 await page.locator('.topline a').first().click();
 await page.locator('.scenario-library summary').focus();
 await page.keyboard.press('Enter');
 await expect(page.locator('.scenario-library')).toHaveAttribute('open','');
 await expect(page.locator('[data-action="paired-start"]:visible')).toHaveCount(14);
 await page.locator('[data-action="paired-start"][data-id="public-search"]').click();
 await expect(page.locator('.paired-game')).toBeVisible();
 expect(state(page).id).toBe('public-search');
 expect(state(page).role).toBe(role);
 await page.locator('[data-action="paired-answer"]').first().click();
 await page.locator('[data-action="paired-next"]').click();
 await expect(page.locator('#scene-title')).toBeFocused();
 expect(state(page).history).toHaveLength(1);
});
