import {createReadingTools,accessibilityPage} from './accessibility/ui.mjs';
import {createEncounterMode} from './encounters/ui.mjs';
import {scenarios,scenarioById,sources,CHECKED} from './data.mjs';
import {startSession,currentNode,choose,advance,previous,recap,remainingSteps} from './engine.mjs';
const main=document.querySelector('#main');
let session=null;
const paired=createEncounterMode({siteRole:'public',main,rerender:(focus=true)=>render(focus),getOriginalSession:()=>session,resetOriginalSession:()=>{session=null;},announce:message=>reading.announce(message)});
const reading=createReadingTools({main,siteRole:'public',rerender:(focus=true)=>render(focus)});
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={message:'<path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8v.5Z"/>',bag:'<path d="M6 7h12l2 14H4L6 7Z"/><path d="M9 7V5a3 3 0 0 1 6 0v2"/>',key:'<circle cx="8" cy="8" r="5"/><path d="m12 12 9 9m-4-4 3-3m-6 0 3-3"/>',people:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/><circle cx="9" cy="7" r="4"/>',notes:'<path d="M9 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-4M16 3l5 5-9 9H7v-5l9-9Z"/>'};
const icon=id=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[id]||paths.message}</svg>`;
const sourceLinks=ids=>`<details class="source-details"><summary>Read the sources</summary><ul>${[...new Set(ids)].map(id=>`<li><a href="${esc(sources[id].url)}" target="_blank" rel="noopener noreferrer">${esc(sources[id].title)} ↗</a></li>`).join('')}</ul></details>`;
const focusMain=()=>{const heading=main.querySelector?.('h1');(heading||main).focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});};
function home(){
 return `<section class="home-intro" aria-labelledby="game-title"><p class="eyebrow">REPUBLIC OF IRELAND · PUBLIC PERSPECTIVE</p><h1 id="game-title" lang="en-IE" data-no-translate>Stopped: Both Sides</h1><p class="lead">An interactive learning game for the public and Gardaí.</p><p class="lead">Practise what you can ask and what you may need to do when Gardaí stop, question, search or arrest you. Explore the same encounter from either side.</p><div class="context-note"><span>14 shared situations</span><span>No timer</span><span>No sign-up</span></div></section>${paired.landing()}<p class="focus-note">Take your time. You can revisit any choice. Your score reflects learning in the game; your rights never depend on it.</p>
 <details class="single-mode"><summary>Individual practice · original English scenarios</summary><p>These original English scenarios focus on one role. The shared situations above include both perspectives and are available in English and Irish.</p><div class="scenarios" lang="en-IE" data-no-translate>${scenarios.map((s,i)=>`<article class="scenario"><div class="card-top"><span class="scene-icon">${icon(s.icon)}</span><span class="scene-number">SITUATION ${String(i+1).padStart(2,'0')}</span></div><h2>${esc(s.title)}</h2><p class="person">${esc(s.person)}</p><p class="description">${esc(s.description)}</p><p class="small-note">${esc(s.minutes)}</p><button class="primary secondary scenario-action" data-action="start" data-id="${s.id}" aria-label="Explore this situation: ${esc(s.title)}">Explore this situation <span aria-hidden="true">→</span></button></article>`).join('')}</div></details>`;
}
function game(){
 if(session.complete)return summary();
 const s=scenarioById[session.scenarioId],node=currentNode(session),selected=session.selected,choice=selected===null?null:node.choices[selected],remaining=remainingSteps(session),total=session.history.length+remaining.max;
 return `${paired.legacyBar(session)}<div class="topline"><a href="#play" class="text-button">← All situations</a><span>${esc(s.title)} · Decision ${session.history.length+1}</span></div><div class="progress" role="progressbar" aria-label="Decisions completed on this path" aria-valuenow="${session.history.length}" aria-valuemin="0" aria-valuemax="${total}" aria-valuetext="${session.history.length} completed; ${remaining.min===remaining.max?remaining.min:`${remaining.min} to ${remaining.max}`} remaining"><span style="width:${session.history.length/total*100}%"></span></div><div class="game-grid"><section class="story" aria-labelledby="scene-title"><p class="eyebrow">${esc(s.context)}</p><h1 id="scene-title">${esc(node.title)}</h1><p class="story-text">${esc(node.story)}</p>${node.quote?`<blockquote class="quote">${esc(node.quote)}</blockquote>`:''}<div class="character"><strong>${esc(s.person)}</strong>Fictional situation · Republic of Ireland</div></section><section aria-labelledby="choice-title"><div class="prompt"><h2 id="choice-title">${esc(node.prompt)}</h2><p>${choice?'Your choice is selected. Read what matters below.':'Choose a response to explore what it means.'}</p></div><div class="choices">${node.choices.map((c,i)=>`<button class="choice ${i===selected?'selected':''}" data-action="choose" data-index="${i}" ${choice?'disabled':''} aria-pressed="${i===selected}"><span class="choice-letter" aria-hidden="true">${String.fromCharCode(65+i)}</span><span>${esc(c.text)}</span></button>`).join('')}</div>${choice?`<section class="feedback ${choice.review?'revisit':''}" id="feedback" tabindex="-1" aria-labelledby="feedback-title"><p class="eyebrow">${choice.review?'A POINT TO REVISIT':'MAKING SENSE OF YOUR CHOICE'}</p><h2 id="feedback-title">${choice.review?'There is more to consider.':'Here is what matters.'}</h2><p>${esc(choice.feedback)}</p><div class="lesson"><strong>The learning point</strong><p>${esc(node.lesson)}</p></div><div class="phrase"><span>${s.id==='fair-treatment'?'SOMETHING TO REMEMBER':'WORDS YOU COULD USE'}</span>${esc(node.phrase)}</div>${sourceLinks(node.sources)}<button class="primary" data-action="next">${choice.next==='end'?'See your learning recap':'Continue the situation'} <span aria-hidden="true">→</span></button></section>`:''}</section></div><div class="topline game-note">${session.history.length?'<button class="text-button" data-action="back">← Revisit the previous decision</button>':'<span>No timer. Take the time you need.</span>'}<a href="#rights">Rights & sources</a></div><p class="game-note">The next scene is fictional. No choice guarantees an outcome or excuses mistreatment. This game cannot decide whether a particular stop, search or arrest is lawful.</p>`;
}
function summary(){const s=scenarioById[session.scenarioId],items=recap(session),review=items.filter(x=>x.choice.review).length;return `${paired.legacyBar(session)}<div class="topline"><a href="#play" class="text-button">← All situations</a><span>${esc(s.title)}</span></div><div class="summary-heading"><div class="summary-icon" aria-hidden="true">✓</div><p class="eyebrow">YOUR LEARNING RECAP</p><h1>More informed.<br>More questions you can ask.</h1><p>You explored ${items.length} decisions with ${esc(s.person.split(',')[0])}.${review?` There ${review===1?'is 1 point':`are ${review} points`} to revisit below.`:' Here are the key points from your path.'}</p><p class="small-note">This is a record of learning, not a prediction of police conduct or a judgment on someone’s response under pressure.</p></div><div class="summary-grid"><ol class="summary-list">${items.map(({node,choice},i)=>`<li class="summary-item">${choice.review?'<span class="badge">Worth revisiting</span>':''}<h2>${i+1}. ${esc(node.title)}</h2><p class="chosen">You chose: ${esc(choice.text)}</p><p>${esc(node.lesson)}</p>${sourceLinks(node.sources)}</li>`).join('')}</ol><aside class="summary-aside"><h2>Keep exploring</h2><p>A different choice can raise a different question. Replay this situation or meet another character.</p><button class="primary" data-action="start" data-id="${s.id}">Replay this situation</button><a href="#play" class="primary secondary">Choose another situation</a><a href="#rights" class="primary secondary">Rights & sources</a><p class="small-note">For a real incident, use current sources and speak with a solicitor about your circumstances.</p></aside></div>`;}
function rights(){return `<div class="content-page"><p class="eyebrow">READ. CHECK. ASK FOR ADVICE.</p><h1>Rights & sources</h1><p class="page-lead">The source behind a learning point is part of the game. Use these resources to check the detail and find appropriate support.</p>${session?`<p><a class="primary secondary" href="#scenario/${session.scenarioId}">${session.complete?'Back to your recap':'Return to your situation'} →</a></p>`:''}<section class="info-block important"><h2>Start with the right question</h2><ul><li><strong>During an encounter:</strong> “Why am I being stopped? Am I free to leave?”</li><li><strong>If a requirement is unclear:</strong> “What legal power applies, and what do I have to provide?”</li><li><strong>At a station:</strong> “I want a solicitor. Please explain my rights and the help available.”</li></ul><p>These are learning prompts, not a script guaranteed to produce a particular result.</p></section><section class="info-block"><h2>Choosing a source</h2><p>Citizens Information explains the general position. Revised legislation sets out particular powers. A solicitor can apply the law to your circumstances. INAR and ICCL contribute rights and community perspectives.</p><p>Sources checked on <strong>${CHECKED}</strong>. This is an educational prototype awaiting review by a practising Irish criminal-law solicitor and community contributors. A check date is not legal approval.</p><p>Some older guides refer to GSOC. <strong>Fiosrú</strong> replaced it in April 2025; use the current Fiosrú process for complaints. This game does not submit reports or complaints.</p>${sourceLinks(['fiosru'])}</section><div class="section-heading"><h2>Explore the original resources</h2></div><div class="sources-grid">${Object.values(sources).map(s=>`<a class="source-card" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer"><strong>${esc(s.title)} ↗</strong><span>${esc(s.note)}</span></a>`).join('')}</div><section class="info-block"><h2>Scope matters</h2><p>The situations cover selected street enquiries, a drug-search power, arrest, custody, young people and complaints. They do not cover every police power, road-traffic stop, immigration or border check, protest, home search, bail condition or court process.</p><p>Do not apply a street-enquiry example to a different legal setting. For immediate danger, contact the emergency services on 112 or 999.</p></section></div>`;}
function about(){return `<div class="content-page"><p class="eyebrow">ABOUT THE PROJECT</p><h1>Learn through situations.<br>Make room for lived experience.</h1><p class="page-lead">Stopped: Both Sides is an independent learning prototype by Sam O’Brien-Olinger / Sam Tim Solutions.</p><section class="info-block"><h2>How the game works</h2><p>Six fictional people encounter questions about Garda powers, rights and responsibilities. Choose a response, read the explanation and follow the situation to a learning recap. You can revisit a decision or replay a route.</p><p>There are no lives to lose, countdowns or rewards for avoiding arrest. An arrest does not establish guilt, and exercising a right does not guarantee a particular outcome.</p></section><section class="info-block important"><h2>Rights belong to everyone</h2><p>Feeling anxious, angry or confused does not remove your rights. Nobody is responsible for someone else’s discriminatory treatment. A suggestion to avoid physical confrontation is not an endorsement of an unlawful action.</p><p>The INAR/ICCL report informs the attention to racial profiling and community experience. The characters are invented; they do not represent individual research participants or entire communities.</p>${sourceLinks(['inarReport'])}</section><section class="info-block"><h2>A prototype with space for input</h2><p>Potential contributions from INAR, ICCL, solicitors, youth organisations and affected communities include reviewing legal wording, shaping scenarios, testing accessibility and developing carefully reviewed translations. No partnership or endorsement is claimed.</p><p>Priority areas for further development include Traveller and Roma perspectives, disability and communication needs, immigration and border contexts, and facilitator-led learning. These are opportunities for collaboration, not completed or commissioned work.</p></section><section class="info-block"><h2>Information and privacy</h2><p>This is general educational information, not legal advice. The source review date is ${CHECKED}; the prototype has not been signed off by a practising solicitor. Laws, guidance and procedures can change.</p><p>The game has no account form, analytics or complaint collection. Fictional choices, scores and a resume point are saved in this browser. The site-switch button carries this learning record to the companion site in the link. You can review or clear local records under Scores & progress. Separate browsers do not automatically sync. Hosting providers may keep standard access logs; external sources have their own privacy arrangements.</p></section><a href="#play" class="primary">Choose a situation →</a></div>`;}
function render(focus=true){try{const hash=location.hash.slice(1)||'play';
 if(hash==='accessibility'){main.innerHTML=accessibilityPage();document.title='Accessibility | Stopped: Both Sides';paired.updateSiteLink(hash);reading.decorate(hash);document.querySelectorAll('[data-nav]').forEach(a=>a.removeAttribute('aria-current'));if(focus)focusMain();return;}
 if(paired.handles(hash)){
  main.innerHTML=paired.view(hash);
  document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===(hash.startsWith('progress')?'progress':'encounters'))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  document.title='Play both sides | Stopped: Both Sides';paired.updateSiteLink(hash);reading.decorate(hash);if(focus)focusMain();return;
 }
 let view='play';if(hash.startsWith('scenario/')){const id=hash.slice(9);if(!Object.hasOwn(scenarioById,id)){main.innerHTML='<div class="content-page"><h1>Situation not found</h1><p>Choose one of the six available situations.</p><a class="primary" href="#play">All situations</a></div>';if(focus)focusMain();return;}if(!session||session.scenarioId!==id)session=startSession(id);if(reading.language==='ga'){paired.transferOriginal(session,focus);return;}main.innerHTML=game();}else if(hash==='rights'){view='rights';main.innerHTML=rights();}else if(hash==='about'){view='about';main.innerHTML=about();}else{main.innerHTML=home();}document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=hash.startsWith('scenario/')?`${scenarioById[session.scenarioId].title} | Stopped: Both Sides`:`${view==='play'?'Stopped: Both Sides':view==='rights'?'Rights & sources':'About the project'} | Stopped: Both Sides — public perspective`;paired.updateSiteLink(hash);reading.decorate(hash);if(focus)focusMain();}catch(error){main.innerHTML='<div class="error"><h1>The game could not load.</h1><p>Refresh the page to try again. You can still read <a href="https://www.citizensinformation.ie/en/justice/arrests/questioning-and-surveillance/">Citizens Information’s guidance</a>.</p></div>';console.error(error);}}
main.addEventListener('click',event=>{if(paired.handleClick(event))return;const button=event.target.closest('button[data-action]');if(!button)return;switch(button.dataset.action){case 'start':session=startSession(button.dataset.id);if(location.hash===`#scenario/${session.scenarioId}`)render();else location.hash=`scenario/${session.scenarioId}`;break;case 'choose':{const next=choose(session,Number(button.dataset.index));if(next===session)return;session=next;render(false);const feedback=document.querySelector('#feedback');feedback?.focus({preventScroll:true});feedback?.scrollIntoView({behavior:'instant',block:'nearest'});break;}case 'next':{const next=advance(session);if(next===session)return;session=next;render();break;}case 'back':session=previous(session);render();break;}});
document.querySelector('.skip')?.addEventListener('click',event=>{event.preventDefault();main.focus({preventScroll:true});main.scrollIntoView({block:'start',behavior:'instant'});});
window.addEventListener('hashchange',()=>render());
render(false);
