import {hasOwn} from '../compatibility.mjs';
import {createReadingTools,accessibilityPage} from '../accessibility/ui.mjs';
import {createEncounterMode} from '../encounters/ui.mjs';
import {scenarios,scenarioById,sources,CHECKED,groups,PUBLIC_COMPANION} from './data.mjs';
import {startSession,currentNode,choose,advance,previous,recap,remainingSteps} from './engine.mjs';
const main=document.querySelector('#main');
let session=null;
const paired=createEncounterMode({siteRole:'garda',main,rerender:(focus=true)=>render(focus),getOriginalSession:()=>session,resetOriginalSession:()=>{session=null;},announce:message=>reading.announce(message)});
const reading=createReadingTools({main,siteRole:'garda',rerender:(focus=true)=>render(focus)});
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={message:'<path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8v.5Z"/>',bag:'<path d="M6 7h12l2 14H4L6 7Z"/><path d="M9 7V5a3 3 0 0 1 6 0v2"/>',people:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/><circle cx="9" cy="7" r="4"/>',notes:'<path d="M9 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-4M16 3l5 5-9 9H7v-5l9-9Z"/>'};
const icon=id=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[id]||paths.message}</svg>`;
const sourceLinks=ids=>`<details class="source-details"><summary>Evidence behind this explanation</summary><ul>${[...new Set(ids)].map(id=>`<li><a href="#evidence/${id}">${esc(sources[id].short)}</a><span class="citation-context">${esc(sources[id].kind)} · ${esc(sources[id].place)}</span></li>`).join('')}</ul></details>`;
const returnToSession=()=>session?`<p><a class="primary secondary" href="#scenario/${session.scenarioId}">${session.complete?'Return to your recap':'Return to your situation'} →</a></p>`:'';
const focusMain=()=>{const heading=main.querySelector?.('h1');(heading||main).focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});};
function home(){
 return `<section class="home-intro" aria-labelledby="game-title"><p class="eyebrow">REPUBLIC OF IRELAND · GARDA PERSPECTIVE</p><h1 id="game-title" lang="en-IE" data-no-translate>Stopped: Both Sides</h1><p class="lead">An interactive learning game for the public and Gardaí.</p><p class="lead">Practise checking assumptions, evidence and legal grounds when deciding to stop or search someone. See how the same encounter is experienced from either side.</p><div class="context-note"><span>14 shared situations</span><span>No timer</span><span>No sign-up</span></div></section>${paired.landing()}<p class="focus-note">Take your time. You can revisit any choice. Your score reflects learning in the game; your rights never depend on it.</p>
 <details class="single-mode"><summary>Individual practice · original English scenarios</summary><p>These original English scenarios focus on one role. The shared situations above include both perspectives and are available in English and Irish.</p><div class="scenarios" lang="en-IE" data-no-translate>${scenarios.map((s,i)=>`<article class="scenario"><div class="card-top"><span class="scene-icon">${icon(s.icon)}</span><span class="scene-number">SITUATION ${String(i+1).padStart(2,'0')}</span></div><h2>${esc(s.title)}</h2><p class="person">${esc(s.person)}</p><p class="description">${esc(s.description)}</p><p class="small-note">${esc(s.minutes)}</p><button class="primary secondary scenario-action" data-action="start" data-id="${s.id}" aria-label="Explore this situation: ${esc(s.title)}">Explore this situation <span aria-hidden="true">→</span></button></article>`).join('')}</div></details>`;
}
function game(){
 if(session.complete)return summary();
 const s=scenarioById[session.scenarioId],node=currentNode(session),selected=session.selected,choice=selected===null?null:node.choices[selected],remaining=remainingSteps(session),total=session.history.length+remaining.max;
 return `${paired.legacyBar(session)}<div class="topline"><a href="#play" class="text-button">← All situations</a><span>${esc(s.title)} · Decision ${session.history.length+1}</span></div><div class="progress" role="progressbar" aria-label="Decisions completed on this path" aria-valuenow="${session.history.length}" aria-valuemin="0" aria-valuemax="${total}" aria-valuetext="${session.history.length} completed; ${remaining.min===remaining.max?remaining.min:`${remaining.min} to ${remaining.max}`} remaining"><span style="width:${session.history.length/total*100}%"></span></div>
 <div class="game-grid"><section class="story" aria-labelledby="scene-title"><p class="eyebrow">${esc(s.context)}</p><h1 id="scene-title">${esc(node.title)}</h1><p class="story-text">${esc(node.story)}</p>${node.facts.length?`<div class="facts"><h2>Keep these facts in view</h2><ul>${node.facts.map(f=>`<li>${esc(f)}</li>`).join('')}</ul></div>`:''}<div class="character"><strong>Your role: ${esc(s.person)}</strong>Fictional situation · Republic of Ireland</div></section>
 <section aria-labelledby="choice-title"><div class="prompt"><h2 id="choice-title">${esc(node.prompt)}</h2><p>${choice?'Read the reasoning, then continue.':'Choose a response to examine its reasoning.'}</p></div><div class="choices">${node.choices.map((c,i)=>`<button class="choice ${i===selected?'selected':''}" data-action="choose" data-index="${i}" ${choice?'disabled':''} aria-pressed="${i===selected}"><span class="choice-letter" aria-hidden="true">${String.fromCharCode(65+i)}</span><span>${esc(c.text)}</span></button>`).join('')}</div>
 ${choice?`<section class="feedback ${choice.review?'revisit':''}" id="feedback" tabindex="-1" aria-labelledby="feedback-title"><p class="eyebrow">${esc(node.concept)}</p><h2 id="feedback-title">${choice.review?'Pause and examine the basis.':'A considered approach on these facts.'}</h2><p>${esc(choice.feedback)}</p><div class="lesson"><strong>The learning point</strong><p>${esc(node.lesson)}</p></div><div class="phrase"><span>A QUESTION TO CARRY FORWARD</span>${esc(node.phrase)}</div>${sourceLinks(node.sources)}<button class="primary" data-action="next">${choice.next==='end'?'See your reflection recap':'Continue the situation'} <span aria-hidden="true">→</span></button></section>`:''}</section></div>
 <div class="topline game-note">${session.history.length?'<button class="text-button" data-action="back">← Revisit the previous decision</button>':'<span>No timer. Take time to examine the facts.</span>'}<a href="#evidence">Evidence & sources</a></div><p class="game-note">The explanations concern the facts stated in this exercise. They do not determine a real incident’s lawfulness or diagnose a learner’s attitudes.</p>`;
}
function summary(){
 const s=scenarioById[session.scenarioId],items=recap(session);
 return `${paired.legacyBar(session)}<div class="topline"><a href="#play" class="text-button">← All situations</a><span>${esc(s.title)}</span></div><div class="summary-heading"><p class="eyebrow">YOUR REFLECTION RECAP</p><h1>What shaped<br>your decision?</h1><p>You explored ${items.length} decisions in the role of ${esc(s.person.toLowerCase())}. Review the reasoning and choose a question to bring to your next learning discussion.</p><p class="small-note">This recap records choices in a fictional exercise. It is not a qualification, a performance appraisal or a measure of personal bias.</p></div><div class="summary-grid"><ol class="summary-list">${items.map(({node,choice},i)=>`<li class="summary-item">${choice.review?'<span class="badge">Reasoning to revisit</span>':''}<h2>${i+1}. ${esc(node.title)}</h2><p class="chosen">You chose: ${esc(choice.text)}</p><p>${esc(choice.feedback)}</p><p><strong>${esc(node.concept)}:</strong> ${esc(node.lesson)}</p><p class="recap-question">${esc(node.phrase)}</p>${sourceLinks(node.sources)}</li>`).join('')}</ol><aside class="summary-aside"><h2>Try another perspective</h2><p>Replay with a different choice. Notice what changes in the next scene and what remains part of the legal and evidential standard.</p><button class="primary" data-action="start" data-id="${s.id}">Replay this situation</button><a href="#play" class="primary secondary">Choose another situation</a><a href="#about" class="primary secondary">Use in a learning discussion</a><a href="${PUBLIC_COMPANION}" class="text-button companion-link" target="_blank" rel="noopener noreferrer">Explore the public’s perspective ↗</a></aside></div>`;
}
function sourceCard(id,s,open){
 return `<details class="evidence-record" id="source-${id}" tabindex="-1" ${open===id?'open':''}><summary><span class="evidence-kind">${esc(s.kind)} · ${esc(s.year)}</span><span class="evidence-title">${esc(s.title)}</span><span class="evidence-authors">${esc(s.authors)}</span></summary><div class="evidence-body"><p class="source-meta">${esc(s.publication)} · ${esc(s.place)}</p><p><strong>What it contributes</strong><br>${esc(s.note)}</p><p><strong>Limits to interpretation</strong><br>${esc(s.limit)}</p><p><strong>How this informed the design</strong><br>${esc(s.use)}</p><p class="access-note">Review access: ${esc(s.access)}.</p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Read the original source ↗</a></div></details>`;
}
function evidence(open=''){
 const academic=Object.values(sources).filter(s=>s.kind.startsWith('Academic')).length;
 return `<div class="content-page evidence-page"><p class="eyebrow">CHECK THE EVIDENCE. KEEP ITS LIMITS IN VIEW.</p><h1>Evidence & sources</h1><p class="page-lead">A selected review of ${academic} academic publications, alongside Irish law, professional guidance and community research. Each source explains how it informed the game.</p>${returnToSession()}
 <section class="info-block important"><h2>What this review covers</h2><p>The reading spans suspicion, stereotyping, police culture, Traveller and minority experiences, procedural justice, search patterns and training. International findings inform reflection; Irish law governs the Irish examples.</p><p>Checked ${CHECKED}. This is a substantial, non-exhaustive evidence review, not a systematic review of all literature. Access ranges from selected full-text sections to abstracts and publisher descriptions, as labelled below. The game has not been independently evaluated.</p></section>
 <nav class="evidence-nav" aria-label="Evidence topics">${Object.entries(groups).map(([id,label])=>`<a href="#evidence/group-${id}">${esc(label)}</a>`).join('')}</nav>
 <section class="info-block"><h2>Three distinctions worth keeping</h2><dl class="evidence-distinctions"><dt>A pattern and its cause</dt><dd>A disparity calls for careful inquiry. Counts alone cannot identify every mechanism or determine an individual case.</dd><dt>A fair explanation and a lawful power</dt><dd>Respectful communication matters alongside a valid basis for the action. One does not replace the other.</dd><dt>Learning and changed practice</dt><dd>Knowing more or completing a game does not establish lasting changes in real encounters.</dd></dl><p class="small-note">These are design conclusions drawn from the sources below, including studies with mixed and null findings.</p>${sourceLinks(['carvalho','petersen','fraRacism'])}</section>
 ${Object.entries(groups).map(([group,label])=>`<section class="evidence-group" id="group-${group}" tabindex="-1" aria-labelledby="heading-${group}"><h2 id="heading-${group}">${esc(label)}</h2>${Object.entries(sources).filter(([,s])=>s.group===group).map(([id,s])=>sourceCard(id,s,open)).join('')}</section>`).join('')}
 <section class="info-block"><h2>Keep the reading open</h2><p>This collection is a starting point for review and development. Important next steps include specialist case-law review, further non-English European literature, community-led additions and evaluation with Garda learners.</p><p>Source authors and organisations have not approved this interpretation or endorsed the game.</p></section></div>`;
}
function about(){
 return `<div class="content-page"><p class="eyebrow">ABOUT THE GARDA PERSPECTIVE</p><h1>Examine the decision.<br>Keep the person in view.</h1><p class="page-lead">Stopped: Both Sides helps Garda learners recognise assumptions, examine their evidence and reflect on fair treatment during stop-and-search decisions.</p>${returnToSession()}
 <section class="info-block"><h2>How it works</h2><p>Take the Garda role in eight fictional situations. Choose a response, read the explanation and follow the next scene. Some choices lead to an additional opportunity to reconsider. You can revisit earlier decisions, replay a route or open the research at any point.</p><p>The aim is to improve the quality of reasoning. There are no points for searches, arrests or avoiding every intervention, and no personal bias score. A scenario can have more than one reasonable next step.</p></section>
 <section class="info-block important"><h2>A learning companion</h2><p>This independent prototype is for reflection between encounters. It cannot assess live incidents, provide operational authorisation or certify that a Garda’s decisions are free from bias.</p><p>The Irish examples include section 23 of the Misuse of Drugs Act and the distinction between voluntary enquiries and specific legal demands. Other powers, case law, urgent threats, custody and search procedures need their own current professional guidance.</p><p>It is not official Garda training. Legal, operational and community review remain outstanding.</p></section>
 <section class="info-block"><h2>Use it in a short learning discussion</h2><ol class="discussion-steps"><li><strong>Play one situation.</strong> Say which facts matter before looking at the feedback.</li><li><strong>Compare the reasoning.</strong> Discuss the grounds, alternative explanations, identity cues and the person’s experience.</li><li><strong>Return later.</strong> Revisit the situation and consider one practical question for briefing or supervision.</li></ol><p>Facilitators should use fictional or appropriately anonymised examples and make room for disagreement supported by law and evidence. The activity should not be used as a staff appraisal.</p>${sourceLinks(['miller','wouters','merla'])}</section>
 <section class="info-block"><h2>Connected to the Garda Decision Making Model</h2><p>The learning prompts support gathering and checking information, assessing risk, considering the operational environment and legal powers, comparing options, and reviewing action. Human rights and ethics run through the decision.</p><p>This is an educational interpretation of the public framework. Members should use the current official model, policy and training in their work.</p>${sourceLinks(['model','ethics'])}</section>
 <section class="info-block"><h2>Help shape a stronger version</h2><p>Garda educators, independent legal specialists, INAR, ICCL, youth organisations, disability advocates, Traveller and Roma organisations, and other affected communities could help refine the situations and challenge missing perspectives.</p><p>Priorities include legal validation, community co-design, accessibility testing, reviewed translations and an independent evaluation of learning and transfer to practice. These are opportunities for collaboration; no partnership or approval is claimed.</p></section>
 <section class="info-block"><h2>Your choices and privacy</h2><p>The game asks for no account or incident details. Fictional choices, scores and a resume point are saved in this browser. The site-switch button carries this learning record to the companion site in the link. Review or clear local records under Scores & progress. Separate browsers do not automatically sync. There are no analytics or submissions to a game server. The hosting provider may keep standard access logs; external sources have their own privacy arrangements.</p></section>
 <section class="info-block"><h2>Two perspectives on an encounter</h2><p>Created by Sam O’Brien-Olinger / Sam Tim Solutions as a companion to the public rights-learning game. The scenarios are invented and do not reproduce participants’ experiences from any cited study.</p><a class="text-button" href="${PUBLIC_COMPANION}" target="_blank" rel="noopener noreferrer">Visit the public perspective ↗</a></section><a href="#play" class="primary">Choose a situation →</a></div>`;
}
function notFound(){return '<div class="content-page"><h1>This page was not found.</h1><p>Choose a situation or explore the evidence library.</p><a class="primary" href="#play">All situations</a></div>';}
function render(focus=true){
 try{
  const hash=location.hash.slice(1)||'play';
 if(hash==='accessibility'){main.innerHTML=accessibilityPage();document.title='Accessibility | Stopped: Both Sides';paired.updateSiteLink(hash);reading.decorate(hash);document.querySelectorAll('[data-nav]').forEach(a=>a.removeAttribute('aria-current'));if(focus)focusMain();return;}
 if(paired.handles(hash)){
  main.innerHTML=paired.view(hash);
  document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===(hash.startsWith('progress')?'progress':'encounters'))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  document.title='Play both sides | Stopped: Both Sides';paired.updateSiteLink(hash);reading.decorate(hash);if(focus)focusMain();return;
 }
 let view='play',target='';
  if(hash.startsWith('scenario/')){const id=hash.slice(9);if(!hasOwn(scenarioById,id)){main.innerHTML=notFound();view='missing';}else{if(!session||session.scenarioId!==id)session=startSession(id);if(reading.language==='ga'){paired.transferOriginal(session,focus);return;}main.innerHTML=game();}}
  else if(hash==='evidence'||hash.startsWith('evidence/')){view='evidence';const id=hash.slice(9);if(id&&!hasOwn(sources,id)&&!(id.startsWith('group-')&&hasOwn(groups,id.slice(6)))){main.innerHTML=notFound();view='missing';}else{main.innerHTML=evidence(id);target=id?(hasOwn(sources,id)?`source-${id}`:id):'';}}
  else if(hash==='about'){view='about';main.innerHTML=about();}
  else if(hash==='play'||hash==='main'){main.innerHTML=home();}
  else{view='missing';main.innerHTML=notFound();}
  document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  document.title=`${view==='evidence'?'Evidence & sources':view==='about'?'About the Garda perspective':view==='missing'?'Page not found':hash.startsWith('scenario/')&&session?scenarioById[session.scenarioId].title:'Stopped: Both Sides'} | Stopped: Both Sides — Garda perspective`;
  paired.updateSiteLink(hash);reading.decorate(hash);
  if(focus){if(target){const element=document.getElementById(target);element?.focus({preventScroll:true});element?.scrollIntoView({block:'start',behavior:'instant'});}else focusMain();}
 }catch(error){main.innerHTML='<div class="error"><h1>The game could not load.</h1><p>Refresh the page to try again. You can still read the <a href="https://www.garda.ie/en/about-us/publications/policy-documents/garda-decision-making-model.pdf">Garda Decision Making Model</a>.</p></div>';console.error(error);}
}
main.addEventListener('click',event=>{if(paired.handleClick(event))return;
 const button=event.target.closest('button[data-action]');if(!button)return;
 switch(button.dataset.action){
  case 'start':session=startSession(button.dataset.id);if(location.hash===`#scenario/${session.scenarioId}`)render();else location.hash=`scenario/${session.scenarioId}`;break;
  case 'choose':{const next=choose(session,Number(button.dataset.index));if(next===session)return;session=next;render(false);const feedback=document.querySelector('#feedback');feedback?.focus({preventScroll:true});feedback?.scrollIntoView({behavior:'instant',block:'nearest'});break;}
  case 'next':{const next=advance(session);if(next===session)return;session=next;render();break;}
  case 'back':session=previous(session);render();break;
 }
});
document.querySelector('.skip')?.addEventListener('click',event=>{event.preventDefault();main.focus({preventScroll:true});main.scrollIntoView({block:'start',behavior:'instant'});});
window.addEventListener('hashchange',()=>render());
render(false);
