export {sources,CHECKED,groups,PUBLIC_COMPANION} from './sources.mjs';
const c=(text,feedback,next,review=false)=>({text,feedback,next,review});
const n=(title,story,prompt,concept,lesson,phrase,refs,choices,facts=[],quote='')=>({title,story,prompt,concept,lesson,phrase,sources:refs,choices,facts,quote});
export const scenarios=[
{id:'street',title:'A hunch on the street',person:'Patrol Garda',context:'Alex, 24 · walking home after work',description:'Someone looks away as your patrol approaches. Separate what you saw from what you assumed.',icon:'message',minutes:'5–7 minutes',theme:'First impressions',start:'street-start',nodes:{
'street-start':n('What caught your attention?','You are on foot patrol. Alex is standing beside a closed shop, looking at a phone. Alex looks away when you approach. A recent briefing mentioned thefts in the town, but gave no relevant person description. There is no immediate threat.','What do you do with this first impression?','Observation and interpretation','A first impression is a prompt to examine information. It is not, by itself, a demonstrated legal basis for detention or a search.','What did I observe, and what meaning did I add?',['quinton','model'],[
 c('Check for a specific link to an offence before deciding on contact.','This leaves space to test the initial interpretation without making Alex account for ordinary behaviour.','street-information'),
 c('Ask an open question, making clear that the conversation is voluntary.','An enquiry needs a legitimate purpose and fair selection too. Keep its voluntary status real; consider whether contact is needed at all.','street-enquiry'),
 c('Require Alex to stay while you establish whether the behaviour is innocent.','This places the burden on Alex before a detention power or its conditions have been identified. Reassess the proposed restriction.','street-reset',true)
 ],['Observed: a phone, a closed shop and a change in gaze.','Not established: an offence, a relevant suspect description or a search power.']),
'street-reset':n('You can change course','Alex asks, “Do I have to stay?” You have not identified any legal power requiring Alex to remain. You notice that your earlier wording sounded compulsory.','How do you respond?','Correcting an unsupported escalation','A respectful correction is part of accountable decision-making. Do not build a justification around a decision merely because you have already announced it.','Am I continuing because of evidence, or because I have already committed?',['model','nickerson','questioning'],[
 c('Clarify that Alex is free to leave and reconsider whether an enquiry is needed.','You correct the status of the encounter and return to the evidence.','street-information'),
 c('Say the conversation will end once Alex has proved there is no problem.','That continues to imply a restriction without the missing legal basis.','street-information',true),
 c('Make the same request more politely, without clarifying whether Alex can leave.','Courtesy helps, but it does not resolve an ambiguous or unsupported restriction.','street-information',true)
 ]),
'street-enquiry':n('A choice to decline','You say you are making an enquiry and Alex is free to leave. Alex declines to discuss the evening and starts walking away. Nothing else has changed.','What changes in your assessment?','A voluntary choice is not new evidence','A person declining a genuinely voluntary enquiry has not thereby supplied the missing grounds. Particular identification duties need their own statutory conditions.','Have I turned a right to decline into a reason for suspicion?',['questioning','publicOrder','ethics'],[
 c('Treat the refusal as the additional fact needed for a search.','That converts the voluntary choice into a penalty and still does not identify a search power.','street-information',true),
 c('Ask for name and address as a compulsory routine check.','A compulsory demand requires a relevant power and its conditions; it is not the default response to declining conversation.','street-information',true),
 c('Allow Alex to leave and retain the distinction between refusal and evidence.','This keeps the encounter consistent with the status you explained.','street-information')
 ]),
'street-information':n('A different explanation','The shop’s cleaner comes outside and says Alex is waiting to collect a bicycle after a shift. Nothing links Alex to a specific offence. This account is consistent with what you can see, although you cannot know everything about the evening.','What is the proportionate next decision on these facts?','Testing alternatives','You do not need certainty about every aspect of someone’s life before deciding that the information does not support a coercive intervention.','What evidence would I expect if my initial explanation were wrong?',['nickerson','model','dunham'],[
 c('End the enquiry; there is no identified basis here for detention or search.','The alternative explanation and the absence of a specific link matter. You can remain responsive to genuinely new information.','street-identity'),
 c('Continue a search because the explanation could have been rehearsed.','An explanation being theoretically false is not a new, specific ground to search.','street-identity',true),
 c('Keep Alex nearby until every detail of the shift has been checked.','The unresolved possibility of wrongdoing does not itself supply a detention power.','street-identity',true)
 ]),
'street-identity':n('Same facts. Different identity cue.','Consider two versions of the encounter: Alex is Black Irish in one; Alex is White Irish in the other. Age, clothing, location, behaviour and the available information are identical. Neither identity comes from a relevant suspect description.','What should this comparison change?','Checking consistency','This comparison is a reflection prompt, not a psychological test. A different feeling of suspicion needs examination; it is not additional evidence about either person.','Would I explain the same facts in the same way for someone from another group?',['fraProfiling','forscher','quinton'],[
 c('Apply the same evidential and legal standard, and examine any difference in intuition.','You separate the decision’s basis from the identity cue. The exercise does not diagnose your level of bias.','end'),
 c('Use a lower threshold for the version that feels less familiar.','Familiarity with an identity is not a substitute for a specific evidential link.','end',true),
 c('Conclude that choosing the same answer proves you never act with bias.','A single hypothetical response cannot establish how anyone behaves across real situations.','end',true)
 ])}},
{id:'description',title:'“Matches the description”',person:'Responding Garda',context:'Amina, 27 · near a reported theft',description:'A broad description becomes more specific. Decide which details identify a person and which invite a stereotype.',icon:'notes',minutes:'5–6 minutes',theme:'Descriptions and relevance',start:'description-start',nodes:{
'description-start':n('A very broad description','A caller reports that a bag was stolen outside a café. The initial description is “a Black woman in a dark jacket”. You see Amina, who fits those broad features, among many people nearby. You have no other identifying details or observed behaviour linking Amina to the theft.','What is the strongest next step?','Specificity and relevance','A relevant description can contain appearance information. Its precision, reliability, timing and connection to a particular incident matter; a broad group match should not become a general selection rule.','What distinguishes this person from others who fit the same broad description?',['fraProfiling','minhas'],[
 c('Seek more specific details and check time, place and direction of travel.','You improve the information before attaching the allegation to a particular person.','description-detail'),
 c('Search everyone nearby who fits those two features.','This treats a broad racialised category as an adequate individual connection and leaves the search power unidentified.','description-repair',true),
 c('Remove all appearance information, even if the caller can provide a specific description.','Avoiding stereotypes does not require discarding relevant identifying evidence. Assess its quality and lawful relevance.','description-detail',true)
 ]),
'description-repair':n('Pause the general sweep','Your colleague asks what legal power would authorise the proposed searches and why these particular people were selected. The caller is still available.','How do you improve the decision?','A label is not a legal basis','Naming an investigation does not establish the conditions for searching each person. Return to individual facts and the applicable power.','Can I explain this person’s connection without relying mainly on group membership?',['fraProfiling','model'],[
 c('Treat proximity to the café as enough to search everyone in the category.','Proximity is context, not an automatic replacement for a specific connection and lawful power.','description-detail',true),
 c('Get the fuller description and reassess whether any intervention is justified.','You can change the proposed action before it creates unnecessary intrusion.','description-detail'),
 c('Keep the same selection and record the general report as the grounds.','Recording a weak explanation does not make it more individualised.','description-detail',true)
 ]),
'description-detail':n('A detail that does not fit','The caller now describes a bright yellow panel on the jacket, a red bicycle and a departure several minutes earlier towards the river. Amina has neither the panel nor a bicycle and has been at the café throughout that period.','How do you handle the mismatch?','Confirmation bias','Information that weakens your first interpretation deserves the same attention as information that supports it. Do not silently drop inconvenient details from the description.','Which new facts count against the person I first selected?',['nickerson','model'],[
 c('Keep the original conclusion because the first two features still match.','This gives the broad initial cue more weight than the later distinguishing information.','description-power',true),
 c('Reassess Amina’s connection and redirect enquiries towards the fuller account.','The mismatch is material. The scenario does not establish a basis to search Amina.','description-power'),
 c('Ask Amina to explain why the description changed before allowing departure.','The caller’s correction does not shift the burden onto Amina to disprove involvement.','description-power',true)
 ]),
'description-power':n('When the match is stronger','In a separate variation, the fuller description, direction and timing all match a different person, and a reliable witness provides further incident-specific information. You consider an intervention.','What must still be assessed?','Evidence and authority are separate questions','A stronger evidential connection does not create a universal search power. Identify the action proposed and the applicable Irish legal conditions before using it.','What action is justified by these facts, and what authorises that action?',['model','fraProfiling'],[
 c('The power, its conditions, the quality of the information and a proportionate response.','A specific connection is relevant, but the action still requires its own legal basis and limits.','end'),
 c('Only whether the person shares the witness’s stated ethnic description.','That omits the distinguishing evidence and the separate question of authority.','end',true),
 c('Nothing further: a detailed description authorises any search.','The level of detail does not replace the statute and safeguards governing the chosen action.','end',true)
 ])}},
{id:'search',title:'Grounds for a drug search',person:'Patrol Garda',context:'Niamh, 29 · waiting for a bus',description:'Move from a vague concern to a separate case with specific grounds. Keep legal authority, communication and outcome apart.',icon:'bag',minutes:'6–8 minutes',theme:'Lawful grounds',start:'search-start',nodes:{
'search-start':n('“There is drug activity here”','A briefing mentions drug activity around a bus stop. Niamh is waiting with a bag and appears restless. You have no specific information about Niamh, a drug or an exchange. You consider a search under section 23 of the Misuse of Drugs Act 1977.','What needs attention first?','Context is not individual grounds','Section 23 requires reasonable-cause suspicion of possession of a controlled drug in contravention of the Act. A location label and ordinary restlessness do not automatically meet that test.','What specific information connects this person to the suspected possession?',['drugs','quinton'],[
 c('Treat the briefing as authority to search anyone waiting at that stop.','A location-level concern does not remove the need to assess the person and the statutory conditions.','search-check',true),
 c('Identify the specific facts and legal threshold before deciding whether to search.','This distinguishes useful context from the individual grounds needed for the proposed power.','search-check'),
 c('Request consent in a way that suggests the search is unavoidable.','Acquiescence to pressure does not resolve the absence of established grounds or a valid basis for a search.','search-check',true)
 ]),
'search-check':n('“Do I have a choice?”','Niamh asks whether opening the bag is optional. No further evidence has emerged in this version. You have not established a statutory basis or another valid basis for a search.','How do you respond?','Consent and compulsion','Be honest about the basis of the request. Do not use an apparent choice to hide compulsion or use a refusal to manufacture grounds. Consent searches require their own legal and policy assessment.','Does my language accurately describe what the person is free to decide?',['ethics','drugs','questioning'],[
 c('Explain the position and do not proceed on the present unsupported basis.','This avoids presenting a search as inevitable when no valid basis has been established.','search-specific'),
 c('Say it is optional but that refusing will itself establish grounds.','This turns the apparent choice into a threat and does not supply the missing evidence.','search-specific',true),
 c('Leave the question unanswered so that the person opens the bag voluntarily.','Silence about compulsion can mislead. Clear communication is part of the decision, not an obstacle to it.','search-specific',true)
 ]),
'search-specific':n('A separate case with specific evidence','Now consider a different fictional variation. You directly hear Niamh offer a packet as cocaine and see a cash exchange. For this exercise, assume the observations are reliable, current and sufficient to meet section 23’s reasonable-cause requirement. There is no urgent threat.','What is a defensible next step?','Reasonable cause does not require certainty','Where its conditions are met, section 23 permits a search without a warrant. The exercise assumes those conditions here so that you can examine a justified intervention as well as unsupported ones.','Can I state the power and actual grounds clearly without overstating what I know?',['drugs','ethics'],[
 c('Ignore the observations because challenging bias means never searching anyone.','Fairness includes applying a lawful, evidence-based standard consistently. Avoiding every intervention is not the goal.','search-explain',true),
 c('Describe Niamh as guilty before explaining the search.','Grounds for a search are not a conviction or certainty that the item is an illegal drug.','search-explain',true),
 c('Explain section 23 and the specific observations, and proceed within its limits.','On the stated assumptions, this connects the action to a relevant power and individual evidence.','search-explain')
 ],['Separate variation: these are new facts, not a reward or penalty for your previous choice.','Legal sufficiency is assumed for this exercise; the game cannot determine a real case.']),
'search-explain':n('A challenge to your decision','Niamh asks why you selected them and says previous searches felt humiliating. You still have the stipulated lawful grounds. There is no threat or physical obstruction in this scene.','What should shape the response?','Procedural justice and legal limits','Explain the particular grounds, listen and consider dignity and privacy while keeping the action within the power’s limits. A verbal challenge does not itself prove additional offending.','Can the person understand the reason, even if they disagree with it?',['ethics','weisburd','drugs'],[
 c('Hear the concern, explain the grounds and take reasonable steps to protect dignity.','Lawful authority and respectful treatment are separate responsibilities that need to be met together.','search-result'),
 c('Extend the search as a lesson in cooperating with Gardaí.','Disagreement does not justify a punitive extension of the intrusion.','search-result',true),
 c('Avoid explaining because the search is already lawful.','A valid basis does not make communication and accountability unimportant.','search-result',true)
 ]),
'search-result':n('Nothing is found','The fictional search finds no controlled drug. The search is complete and no other basis for detention has arisen. Your colleague says that the empty result means the search was definitely unlawful.','What is the more careful assessment?','Judging the decision at the time','A result alone does not settle lawfulness: finding nothing does not automatically invalidate earlier grounds, and finding something cannot retrospectively create missing grounds.','Am I judging the original reasoning using information that arrived only afterwards?',['drugs','model'],[
 c('Keep Niamh while you search for a different explanation for the empty result.','The search being complete and no other basis arising matters to ending the restriction.','end',true),
 c('End the detention, record the outcome and review the original grounds and conduct.','You separate the result from the earlier legal test and preserve an honest account for review.','end'),
 c('Remove the record because a search with no find is not useful information.','Excluding negative outcomes would distort later review and learning.','end',true)
 ])}},
{id:'communication',title:'When behaviour is misread',person:'Community Garda',context:'Maya, 34 · a busy public space',description:'Slow answers and limited eye contact can invite assumptions. Explore communication, power and fair treatment.',icon:'people',minutes:'4–6 minutes',theme:'Communication and disability',start:'communication-start',nodes:{
'communication-start':n('“They seem evasive”','You ask Maya a general question while following up a local report. Maya looks down, takes time to answer and asks you to repeat the question. You have no specific evidence connecting Maya to an offence. Your colleague calls the behaviour evasive.','What would improve the assessment?','Behaviour has more than one explanation','A communication difference is not a diagnosis or proof of deception. Attend to the actual information and ask what might help the person understand and respond.','What else could explain what I am seeing?',['crane','minhas','ethics'],[
 c('Repeat the question more forcefully to test whether the hesitation is deliberate.','Pressure may change behaviour without establishing whether the original suspicion was justified.','communication-repair',true),
 c('Describe the hesitation as evidence of concealment in the proposed search grounds.','That turns an interpretation of communication into an untested allegation.','communication-repair',true),
 c('Use one clear question, allow time and check whether communication support would help.','This seeks useful information without equating communication style with guilt.','communication-clarify')
 ]),
'communication-repair':n('The interaction is getting harder','Maya becomes quieter as your questions speed up. No new information about an offence has emerged. You can slow the encounter; there is no urgent safety threat.','What needs to change?','Escalation is not corroboration','A response to the encounter itself should not be automatically treated as confirmation of the original suspicion. Reconsider the pace, wording and purpose.','Did my approach contribute to the reaction I am now interpreting?',['crane','nickerson','ethics'],[
 c('Reduce the pressure, clarify the question and revisit whether further contact is needed.','You can change the interaction and still attend to any genuine new evidence.','communication-clarify'),
 c('Treat the increasing silence as independent confirmation of dishonesty.','The behaviour occurred within the pressure of the interaction and remains open to other explanations.','communication-clarify',true),
 c('Require Maya to explain the communication difficulty before you reconsider the search.','That makes access to fair assessment depend on proving a personal condition.','communication-clarify',true)
 ]),
'communication-clarify':n('A request for time','Maya says, “I am autistic. Please ask one question at a time.” The conversation is voluntary, and Maya asks whether it is necessary to continue. No specific grounds for a coercive intervention have emerged.','What is the best response on these facts?','Individual needs and autonomy','Respect the stated communication need and the actual status of the encounter. Do not assume incapacity, guilt or a need for detention from a diagnosis.','What adjustment has this person asked for, and is further contact justified?',['crane','ethics','questioning'],[
 c('Apply the same fast questioning to demonstrate identical treatment.','Fair treatment can require an appropriate adjustment; identical delivery is not always accessible.','communication-review',true),
 c('Explain that Maya is free to leave, use clear language and end unnecessary questioning.','You respect the requested adjustment without turning it into a reason to retain the person.','communication-review'),
 c('Keep Maya at the station for reassurance because a diagnosis was mentioned.','The disclosure does not itself create a power of detention or establish a protective need.','communication-review',true)
 ]),
'communication-review':n('What belongs in the debrief?','Later, you review the encounter with a supervisor. You want to identify a practical change without diagnosing strangers from their behaviour.','What is the most useful learning point?','Specific adjustments, not new stereotypes','Listen for a person’s needs, consider alternatives and keep observations separate from assumptions. A learning exercise should not create another checklist for labelling people.','How can I make my next enquiry clearer and less presumptive?',['crane','merla'],[
 c('Assume everyone who avoids eye contact is autistic.','That replaces one unsupported inference with another.','end',true),
 c('Assume calm, fluent answers rule out offending.','Communication style does not establish either guilt or innocence.','end',true),
 c('Review question clarity, pace, status and the evidence independently of communication style.','This gives you a repeatable decision process while leaving individual differences open.','end')
 ])}},
{id:'young-person',title:'A young person, an adult assumption',person:'Youth-facing Garda',context:'Jamie, 16 · waiting with friends',description:'Appearance, age and group membership overlap. Examine assumptions about threat and entitlement to care.',icon:'people',minutes:'4–5 minutes',theme:'Age and overlapping identities',start:'young-start',nodes:{
'young-start':n('“Old enough to know better”','Jamie is a tall, Black Irish 16-year-old waiting with two friends near a bus stop. You know Jamie’s age. Nobody has reported threatening conduct or linked the group to a particular offence. A colleague assumes Jamie is an adult and suggests searching the group.','What should guide your response?','Adultification and group assumptions','Do not replace known age with an impression based on appearance. Being in a group does not automatically establish individual grounds for search.','Am I assigning greater threat or responsibility than the facts support?',['goff','solhjell','ethics'],[
 c('Use the known age and assess each person’s actual behaviour and any applicable power.','You retain the relevant fact and resist treating the group as a single allegation.','young-contact'),
 c('Treat Jamie as an adult because height makes that seem reasonable.','The known age is stronger information than the impression.','young-contact',true),
 c('Search the whole group so that nobody feels singled out.','Applying an unsupported action to more people does not make it fair or lawful.','young-contact',true)
 ]),
'young-contact':n('“Why is it always us?”','Jamie says the group has been questioned several times while waiting for the same bus. The tone is frustrated but not threatening. You still have no specific evidence of an offence.','What is a constructive response?','Cumulative experience','Frustration may reflect repeated contact. It deserves a fair hearing without being treated as proof of wrongdoing or as a complete account of every earlier incident.','Am I hearing an explanation of mistrust as if it were evidence of guilt?',['solhjell','inar','ethics'],[
 c('Take the frustration as enough to justify the search you were considering.','A verbal concern about repeated contact does not supply the missing search grounds.','young-review',true),
 c('Listen, explain the purpose and status of the contact, and avoid unnecessary intervention.','This acknowledges the concern while keeping the decision tied to what is actually known.','young-review'),
 c('Promise that the group will never be approached again in any circumstances.','You cannot guarantee future encounters. Explain the present decision and standards honestly.','young-review',true)
 ]),
'young-review':n('An identity comparison','Replay the same facts with Jamie as a White Irish 16-year-old. Age, clothing, friends, words and conduct are unchanged. The comparison does not introduce a relevant suspect description.','What should remain consistent?','Equal standards, responsive treatment','Use the same threshold for intervention while responding to each person’s needs. An exercise like this supports reflection; it cannot establish that a learner is free of bias.','Have I changed the threshold without receiving any new relevant evidence?',['fraProfiling','goff','forscher'],[
 c('The evidential and legal standard, with age-appropriate communication for either version.','Consistency concerns the grounds and treatment, not a claim that people’s experiences are identical.','end'),
 c('A higher level of suspicion for whichever identity the team encounters less often.','Unfamiliarity is not an incident-specific link.','end',true),
 c('Only the outcome: identical numbers of searches would prove fairness.','Equal totals alone do not establish the quality of individual decisions or treatment.','end',true)
 ])}},
{id:'colleague',title:'“We know that family”',person:'Garda working with a colleague',context:'Patrick, 35 · an Irish Traveller at work',description:'Local knowledge and team confidence can carry untested assumptions. Practise a constructive challenge.',icon:'message',minutes:'5–6 minutes',theme:'Team culture and group stereotypes',start:'colleague-start',nodes:{
'colleague-start':n('A familiar surname','Patrick is unloading tools for a scheduled repair. A colleague recognises the surname, identifies Patrick as an Irish Traveller and says, “We have had trouble with that family before.” There is no information connecting Patrick or the tools to an offence.','How do you handle the colleague’s confidence?','Association is not individual evidence','A reputation attached to a family or community does not establish what this person has done. Examine the specific information and its relevance.','What do we know about this individual, beyond an association?',['mulcahy','obrien','ethics'],[
 c('Treat the colleague’s experience as sufficient grounds for a search.','Experience can point to questions, but it does not replace individual facts and lawful authority.','colleague-pressure',true),
 c('Reject all local information without checking whether any part is specific and current.','Useful information may exist. The task is to assess it, not accept or discard it solely because of who offered it.','colleague-specific',true),
 c('Ask for specific, current information linking Patrick to the suspected offence.','This tests relevance and allows a professional challenge without dismissing the colleague as a person.','colleague-specific')
 ]),
'colleague-pressure':n('“Back me up”','Your colleague says that questioning the proposal undermines the team. No additional facts have been supplied. Patrick asks whether the search is compulsory.','What is a professional response?','Authority and conformity','Supporting colleagues includes raising concerns about an unsupported use of power. A senior or confident voice is not itself evidence.','Can I support the colleague while challenging the proposed action?',['saudelli','ethics'],[
 c('Go ahead now and raise the missing grounds only after the search.','This allows the proposed intrusion to proceed before the concern is addressed.','colleague-specific',true),
 c('State the concern clearly, clarify the power and seek supervisory support if unresolved.','You focus on the decision and use support without treating rank as a legal basis.','colleague-specific'),
 c('Record that the colleague made the decision so that no further action is needed from you.','Attribution alone does not resolve your own responsibility in the encounter.','colleague-specific',true)
 ]),
'colleague-specific':n('What survives a closer look?','The earlier incident involved someone else several years ago. A customer confirms the scheduled repair. Nothing links Patrick to a current offence. Your colleague remains uneasy.','What should happen to the proposed search?','Updating inherited assumptions','Historical association should not substitute for a present, individual basis. Evaluate the current evidence, including information that weakens the proposal.','Would the same facts seem suspicious without the surname or community label?',['mulcahy','nickerson','fraProfiling'],[
 c('Do not search on the present facts; explain the decision and address the assumption with the team.','You respond to the individual situation and preserve an opportunity for wider learning.','colleague-review'),
 c('Search the tools to settle the colleague’s lingering unease.','Unease is not a new fact connecting the tools to an offence or a search power.','colleague-review',true),
 c('Ask Patrick to prove that the entire family is now law-abiding.','Responsibility for a group is not the test for this individual encounter.','colleague-review',true)
 ]),
'colleague-review':n('A useful team debrief','The encounter ends. You want the next briefing to support sound decisions and a better relationship with the community.','What would be a useful follow-up?','Culture and accountability','Review both the individual decision and the language or habits that shaped it. Community perspectives can identify harms that incident records miss.','What team practice would make the next decision easier to justify fairly?',['saudelli','travellerJustice','curran'],[
 c('Treat the issue as solved because no search eventually happened.','The immediate correction matters, but the recurring assumption still deserves attention.','end',true),
 c('Use anonymised learning, review grounds and invite appropriate community-informed input.','This can turn the encounter into a concrete improvement in briefing and supervision.','end'),
 c('Publicly identify Patrick’s family in training materials so the example feels real.','A learning exercise does not need to expose identifiable community members. Use fictional or appropriately anonymised material.','end',true)
 ])}},
{id:'new-evidence',title:'When the facts change',person:'Responding Garda',context:'Daniel, 32 · a corrected report',description:'You have committed to an intervention. New information weakens the basis. Decide what to update and what to record.',icon:'notes',minutes:'4–6 minutes',theme:'Confirmation and outcome bias',start:'update-start',nodes:{
'update-start':n('You have already announced a search','In this fictional exercise, you initially had a lawful basis for a search concerning Daniel. Before it begins, the source corrects a key identification error and the original basis no longer supports the proposed search. No separate ground or urgent threat has arisen.','How do you respond to the change?','Commitment is not evidence','The decision must respond to the information now available. Announcing an action does not oblige you to complete it when its basis has fallen away.','What must change in my decision when a key fact changes?',['model','nickerson'],[
 c('Pause, reassess the basis and discontinue the search on the stated facts.','You adapt the decision instead of defending the earlier commitment.','update-explain'),
 c('Complete a brief search before considering the correction.','A shorter intrusion still requires a valid basis; the correction matters before the search begins.','update-repair',true),
 c('Ask Daniel to disprove the corrected allegation before you cancel the search.','The absence of a current basis cannot be repaired by shifting the burden onto Daniel.','update-repair',true)
 ]),
'update-repair':n('A colleague asks you to review','A colleague points out that the correction arrived before the search. The situation is stable. You can still stop the proposed action.','Which response improves the decision?','Reassessment under social pressure','Review is part of professional judgment. A concern about appearing inconsistent should not displace the available evidence.','Am I protecting the quality of the decision or the appearance of being right?',['model','saudelli'],[
 c('Continue so that the public sees a consistent Garda response.','Consistency with an unsupported earlier plan is not the same as consistency with law and evidence.','update-explain',true),
 c('Treat the challenge as disloyal and defer any reassessment until the debrief.','An immediate, relevant correction should be considered while it can still affect the action.','update-explain',true),
 c('Accept the correction and stop the search on these facts.','Changing course can prevent an avoidable intrusion.','update-explain')
 ]),
'update-explain':n('Explain what changed','You decide not to proceed. Daniel asks why the proposed search was announced in the first place.','What is the clearest response?','Transparency without overclaiming','Explain the relevant change honestly and clarify the person’s present status. Avoid making promises or legal findings beyond what you can establish.','Can I explain the correction in language the person can understand?',['ethics','weisburd'],[
 c('Explain that information was corrected, the search will not proceed and Daniel is free to leave.','This makes the change and the end of the restriction understandable.','update-record'),
 c('Say the search was completed successfully, so there is nothing more to discuss.','That misdescribes what happened and obstructs accountability.','update-record',true),
 c('Promise that the correction proves no part of the encounter could ever be challenged.','You cannot decide every potential complaint or legal issue through that assurance.','update-record',true)
 ]),
'update-record':n('The record matters too','Later, you write the account needed for review under applicable recording procedures. The initial information and the correction are both relevant.','What should the account preserve?','An honest sequence','Preserve the distinction between information available before the decision and information received afterwards. Record a change of course honestly; do not retrofit grounds.','Could a reviewer reconstruct what I knew at each point?',['ethics','model','knox'],[
 c('Only the initial information, because a correction makes the record confusing.','Omitting the correction would conceal a material part of the decision process.','end',true),
 c('The initial basis, correction, timing, action taken and reason for changing course.','This supports meaningful scrutiny of the decision rather than a tidied-up narrative.','end'),
 c('Only that nothing was found, even though no search took place.','A non-search and a search with no find are different events and should not be conflated.','end',true)
 ])}},
{id:'supervision',title:'What the numbers leave out',person:'Supervising sergeant',context:'A fictional stop-and-search review',description:'Equal search success rates look reassuring. Examine selection, patrol patterns and what a training result can really show.',icon:'notes',minutes:'6–8 minutes',theme:'Patterns and organisational learning',start:'supervision-start',nodes:{
'supervision-start':n('An apparently reassuring dashboard','In a made-up dataset, Group A has 60 searches and 12 finds. Group B has 15 searches and 3 finds. Both have a 20% find rate. There is no information here about who was available to be stopped, patrol deployment, the grounds for each search or treatment during it.','What can you conclude about fairness?','Selection and missing information','Equal find rates alone cannot establish that selection or treatment was fair. Disparities require careful inquiry; the table also cannot diagnose every officer as biased.','Who was selected, who was never recorded and what grounds were present?',['pierson','knox','vomfell'],[
 c('The equal rates prove that the search decisions were equally fair.','This overlooks how people entered the searched sample and how the searches were conducted.','supervision-deployment',true),
 c('The different totals prove every decision concerning Group A was discriminatory.','The figures raise questions but do not determine each encounter’s facts or cause.','supervision-deployment',true),
 c('Review individual grounds, selection and deployment before drawing a conclusion.','You identify what the table cannot tell you and avoid both unsupported reassurance and diagnosis.','supervision-deployment')
 ],['Entirely synthetic data: no Garda or community records are used.','Group A: 60 searches · 12 finds · 20% find rate.','Group B: 15 searches · 3 finds · 20% find rate.']),
'supervision-deployment':n('Where patrols are sent','You discover that one area receives more patrol time and that “success” is discussed mainly as the number of searches completed. The records do not distinguish resident population, people present in the area and people linked by reliable evidence to incidents.','What should the review include?','Individual and organisational decisions','Who is encountered depends partly on deployment and priorities. Scrutinise both the context of officer decisions and the quality of the decisions themselves.','What incentives or deployment choices shape who enters the encounter?',['vomfell','agnew','glaser'],[
 c('Examine deployment, grounds, treatment and outcomes with appropriate data safeguards.','This broadens accountability without assuming one benchmark can settle every question.','supervision-training'),
 c('Compare only with resident census proportions and treat that as a complete explanation.','A single denominator cannot answer all questions about street exposure, deployment and lawful selection.','supervision-training',true),
 c('Increase search targets until the number of finds improves.','Volume alone is not a measure of legal quality or fair treatment, and can create pressure for weakly grounded activity.','supervision-training',true)
 ]),
'supervision-training':n('Everyone completed the game','Your team completes these situations and answers a knowledge quiz more accurately. A colleague suggests announcing that bias in Garda search decisions has now been reduced.','What does that result actually support?','Learning is not the same as field impact','Improved quiz answers demonstrate learning on that measure. They do not establish changed operational behaviour, reduced discrimination or lasting effects.','What outcome did we measure, and what are we claiming instead?',['miller','worden','lai','forscher'],[
 c('Claim proven bias reduction because the team passed the learning activity.','That skips the evidence needed to connect participation with real-world decisions and treatment.','supervision-plan',true),
 c('Report the learning result accurately and plan an evaluation of behaviour and experience.','You preserve the useful result without overstating what it demonstrates.','supervision-plan'),
 c('Abandon all training because some studies found no clear effect on disparities.','Different interventions and outcomes need separate assessment. Evidence of limitations should shape design and evaluation.','supervision-plan',true)
 ]),
'supervision-plan':n('A stronger next step','You can support follow-up learning, supervisory review and appropriate evaluation. The aim is to improve decisions and people’s experience, not just completion numbers.','Which plan addresses the main evidence gaps?','Reinforcement and independent evaluation','Combine repeated practice and feedback with lawful, proportionate review of behaviour and community experience. Agree measures and safeguards before collecting operational data.','What would count as improvement, and who should help judge it?',['weisburd','merla','wouters','inar','tansill'],[
 c('Repeat the same quiz immediately and use its score as a permanent performance rating.','Repeated answers can reflect familiarity, and a learning score is not a validated appraisal of a Garda.','end',true),
 c('Collect identifiable incident details in the game so that it feels operational.','This prototype is not designed or approved to hold operational or personal incident data.','end',true),
 c('Use later practice, independent review of grounds and treatment, and community-informed evaluation.','This provides a more credible route to examining transfer and unintended effects. It remains a proposal requiring appropriate governance.','end')
 ])}}
];
export const scenarioById=Object.fromEntries(scenarios.map(s=>[s.id,s]));
